# Your Solution
version: '3.8'
 
services:
  # Book Catalog Service
  book_catalog:
    image: book_catalog
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://mona22_user:fizfQvrI2S190tVy1WJelCTWRort8Mt1@dpg-crlshm08fa8c739t0ekg-a.oregon-postgres.render.com/mona22
 
  # Inventory Management Service
  inventory_management:
    image: inventory_management
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DATABASE_URL=postgresql://mona22_user:fizfQvrI2S190tVy1WJelCTWRort8Mt1@dpg-crlshm08fa8c739t0ekg-a.oregon-postgres.render.com/mona22